### ISSUE TITLE
Few issues when migrating open source of Cloud Foundry Tools

### ISSUE THREAD

**Issue by veredcon** [vscode-elements/elements#163] opened 2024-09-23 09:07 UTC
Hi Adam,

This is a really cool and useful library that we would like to adopt in SAP instead of the deprecated one. Thank you for developing it!

After trying to adopt it in some open source we have I encountered few issues:
https://github.com/SAP/cloud-foundry-tools/pull/296 
1. codicons are not presented well when inside a vscode-element control  e.g.:
![image](https://github.com/user-attachments/assets/82d692ab-1e93-4466-a9ce-d820655dc955)
The paste icon at the end of the textfield cannot be displayed (if it is just outside of the vscode-element there is no issue)
2. You can see I added some styles of Link component, If there was a vscode-link (like in https://github.com/estruyf/vscode-community-ui-toolkit/blob/main/src/link/index.ts) one would not have to take care of it...
3. I have an issue migrating the vscode-single select and I don't understand why, I tried many things  we have there 2 dropdowns that needs to be populated with the selected org and space once they appear.. for some reason I get the selected org as expected (option is selected) but not the selected space (the selected space is correct but not rendered in the spaces dropdown).. 
4. Also I noticed some errors in the console
![image](https://github.com/user-attachments/assets/8df28cdb-f0e5-4d70-a6b4-0b867c210cbf)

I would appreciate your assistance in adopting this lib so it could be chosen for the rest of our SAP repositories using the old webview toolkit.

Thanks!

**Comment by veredcon** [comment] 2024-09-24 05:14
Hi @bendera 

Thank you so much for your prompt reply and the time for investing in this library!
I see, when I add this specific id I do get the icon when running only frontend locally, but as the id is not maintained in the html after `vite build` it is not displayed when running the whole extension. (When I add it manually to the html **dist** I can see the icon). 
I'm wondering why this specific id is required because it wasn't necessary before and it makes it harder to smoothly migrate. For example without this specific stylesheet id I don't have an issue rendering this: 
```
<span class="codicon codicon-clippy"></span></span>
```

**Comment by bendera** [comment] 2024-09-24 17:15
> I have an issue migrating the vscode-single select and I don't understand why, I tried many things we have there 2 dropdowns that needs to be populated with the selected org and space once they appear.. for some reason I get the selected org as expected (option is selected) but not the selected space (the selected space is correct but not rendered in the spaces dropdown)..

Could you please attach a minimalistic reproducible example?

**Comment by bendera** [comment] 2024-09-24 17:49
4. Fixed in the pre-release:

`npm i @vscode-elements/elements@next`

**Comment by veredcon** [comment] 2024-09-25 12:50
> > I have an issue migrating the vscode-single select and I don't understand why, I tried many things we have there 2 dropdowns that needs to be populated with the selected org and space once they appear.. for some reason I get the selected org as expected (option is selected) but not the selected space (the selected space is correct but not rendered in the spaces dropdown)..
> 
> Could you please attach a minimalistic reproducible example?

Sure, thanks Adam!
1. Clone https://github.com/SAP/cloud-foundry-tools.git
2. `git checkout toolkitmig` - this branch contains migration of webview toolkit to this lib. The last commit I added only to reproduce this issue so you will not need to do actual login to Cloud Foundry.
3. `yarn`, `yarn format:fix`, `yarn ci`
4. Click on `Run Extension`
5. Open command palette and choose `CF: Login to Cloud Foundry` 
![image](https://github.com/user-attachments/assets/cba07f7f-a962-48ad-ae76-4e507e713531)

The issue is that when the dropdowns are displayed, they should already be selected on the relevant org and space.
For some reason the space is not being preselected as expected.. (it should be space4 and not space1)
![image](https://github.com/user-attachments/assets/57048fcc-ba02-4fed-a67b-24471f383972)

It has worked with the former vscode-dropdown so I'm trying to understand what am I missing here ...

**Comment by veredcon** [comment] 2024-09-25 12:51
By the way in order to maintain the id of the codicon css after the vite build I have added the following to the `vite.config.js`

```
{
      name: "html-transform",
      transformIndexHtml(html) {
        // Add id="vscode-codicon-stylesheet" to the existing link tag
        return html.replace(/<link rel="stylesheet" href="\.\/assets\/index-[^"]+\.css">/, (match) =>
          match.replace("<link", '<link id="vscode-codicon-stylesheet"')
        );
      },
    },
```

**Comment by bendera** [comment] 2024-09-28 00:18
I fixed many bugs, please install the latest pre-release version from the next channel. I created a minimalistic, reproducible example:
[elements-vue-bug.zip](https://github.com/user-attachments/files/17171356/elements-vue-bug.zip)

The essential part is this:

```vue
<script>
export default {
  name: "HelloWorld",
  data() {
    return {
      orgs: [],
      selectedOrg: '',
    }
  },
  methods: {
    updateSelectedOrg(event) {
      this.selectedOrg = event.target.value;
    },
  },
  mounted() {
    setTimeout(() => {
      const orgs = [
        { guid: 'A', label: 'Lorem' },
        { guid: 'B', label: 'Ipsum' },
        { guid: 'C', label: 'Dolor' }
      ];

      this.orgs = orgs;
      this.selectedOrg = orgs[2].guid;
    }, 1000);
  }
}
</script>

<template>
  <vscode-single-select :value="selectedOrg" @change="updateSelectedOrg">
    <vscode-option v-for="org in orgs" :key="org.guid" :value="org.guid" :selected="org.guid === selectedOrg">{{
      org.label
      }}</vscode-option>
  </vscode-single-select>
  <p>{{ selectedOrg }}</p>
  <select @change="selectedOrg = $event.target.value" :value="selectedOrg">
    <option :value="org.guid" v-for="org in this.orgs" :key="org.guid" :selected="org.guid === selectedOrg">{{
      org.label
    }} ({{ org.guid }})</option>
  </select>
</template>
```

- I simplified the data flow. In the original code a computed state returns the lists. It's unnecessary, the state variables returned by `data()` are already reactive.
- I used only the id instead of the whole object to memorize the selected element.
- setTimeout is used to emulate network traffic.

```
this.orgs = orgs;
this.selectedOrg = orgs[2].guid;
```

This two lines populate the select component with the selectable options and set the selected one. However, in Vue (and every component based framework) the state changes will be collected and the component will be re-rendered in a single step. Because of this, the value of the select component will be set before it will be populated with the available options. So in this case setting the value won't work, but applying the "selected" property on the vscode-option will be fine.

**Comment by bendera** [comment] 2024-09-28 00:20
(The second select is just for comparison.)

**Comment by veredcon** [comment] 2024-09-29 10:42
Thanks a lot @bendera ! Now with the next version it works as expected!  😀🙏
I really appreciate addressing this issue and taking the time to solve it! 
We are expecting to migrate the rest of our repositories soon.

**Closed** 2024-09-29 10:51 UTC
